name: Build and Test Wheels

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - macostest
  # pull_request:
  #   branches:
  #     - macostest

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
        include:
          - os: ubuntu-latest
            python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
            cibw-build: cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64
          - os: macos-latest
            python-version: [3.8, 3.9, 3.10, 3.11]  # 仅在macOS上支持的版本
            cibw-build: cp38-macosx_universal2 cp39-macosx_universal2 cp310-macosx_universal2 cp311-macosx_universal2
          - os: windows-latest
            python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
            cibw-build: cp36-win_amd64 cp37-win_amd64 cp38-win_amd64 cp39-win_amd64 cp310-win_amd64 cp311-win_amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.cibw-build }}
          CIBW_BEFORE_BUILD: pip install cmake
          CIBW_TEST_COMMAND: "python -m unittest discover tests"

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl
